language: cpp
cache:
  directories:
script:
- docker run -v $PWD:$PWD -w $PWD coqorg/coq:8.9 ./travis/build.sh
sudo: no
dist: xenial
os:
- linux
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.net#connectal

  slack:
    secure: mQApKri2F2TZEyLEs530x+snMA8aDdL6o0e/HCVqk3t4pfSfj2OfPQ5edVrvIh+dsFjhX1GNDk94LSmZTS6AVCQ4+VPXORN1VjvB+xIeyP/PsIjSUoWqvS2V0t8CYV5K+5HRJq2H7tNmY4wxZYQnPAAGplsrKgJBxjccMhSqO30=
